# Generated by Django 4.2.1 on 2023-06-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.ManyToManyField(related_name='jobtype', to='core.jobtype'),
        ),
    ]
