# Generated by Django 4.2.1 on 2023-06-14 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_job_job_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='Address',
            new_name='address',
        ),
    ]
