# Generated by Django 4.2.1 on 2023-06-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_user_address_user_country_user_education_user_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='exp',
            field=models.TextField(blank=True, null=True),
        ),
    ]
